name: pyramid-phoenix
channels:
  - birdhouse
  - defaults
  - conda-forge
dependencies:
  - python=2.7.13
  - setuptools=27.2.0
  - curl=7.49.0
  - pyopenssl=17.0
  - cryptography=1.8
  - icu=56
# tests
  - pytest
# pep8
  - flake8
  - pycodestyle
# sphinx
  - sphinx
  - doc8
# phoenix
  - nginx=1.10
  - supervisor=3
  - gunicorn=19
  - requests-oauthlib
  - gevent=1.2
  - lxml=3.7
  - mako=1.0
  - dateparser=0.5
  - python-dateutil=2.6
  - requests=2.12
  - pyyaml=3.12
  - pygments=2.1
  - pytz=2016.4
  - owslib=0.16.0
  - transaction=1.6
  - esgf-pyclient=0.1.8
  - myproxyclient=1.4.4
  - genshi=0.7
# celery
  - celery=3.1
  - kombu=3.0
# mongodb
  - pymongo=3
  - mongodb=3.4
# twitcher
  - webob=1.6.1
  - argcomplete
# phoenix extensions
#  - python-swiftclient=2.4.0
  - threddsclient=0.3.4
#  - python-ldap=2.4.13
  - funcsigs=1.0.2
  - pip:
      - sphinx-autoapi==0.5.0
      - pyramid==1.9.1
      - pyramid-beaker==0.8
      - Beaker==1.9.0
      - pyramid-deform==0.2
      - deform==2.0.4
      - pyramid-chameleon
      - pyramid-mako==1.0.2
      - pyramid-layout==1.0
      - pyramid-celery==3.0.0
      - pyramid-mailer==0.14.1
      - pyramid-storage==0.1.2
  #    - pyramid-ldap==0.1
  #    - pyramid-twitcher==0.3.3
      - pyramid-rpc==0.8
      - colander==1.3.3
      - Authomatic==0.1.0.post1
      - python-openid==2.2.5
  #    - ldappool==1.0
      - WebHelpers2==2.0
      - WebHelpers2_grid==0.1
      - repoze.sendmail==4.2
