name: pyramid-phoenix 
channels:
  - defaults
  - birdhouse
dependencies:
  - python=2 
  - setuptools=23.0.0
  - curl=7.49.0 
  - pyopenssl=0.15.1 
  - cryptography=1.0.2 
  - mako=1.0.4
  - pyyaml=3.11
  - pip:
      - genshi==0.7
